2024-01-18 21:59:54,471:logger:data loaded to vector database successfullu
2024-01-18 22:00:23,262:logger:data loaded to vector database successfully
2024-01-18 22:05:00,822:logger:data loaded to vector database successfullu
2024-01-18 22:07:46,630:logger:data loaded to vector database successfullu
2024-01-18 22:07:56,509:logger:data loaded to vector database successfully
2024-01-18 22:10:31,784:logger:data loaded to vector database successfullu
2024-01-18 22:10:38,968:logger:data loaded to vector database successfully
2024-01-18 22:27:03,343:logger:data loaded to vector database successfullu
2024-01-18 22:27:16,956:logger:data loaded to vector database successfully
2024-01-18 22:28:19,472:logger:data loaded to vector database successfullu
2024-01-18 22:28:22,504:logger:data loaded to vector database successfully
2024-01-18 22:29:26,217:logger:data loaded to vector database successfullu
2024-01-18 22:29:29,126:logger:data loaded to vector database successfully
2024-01-18 22:30:38,666:logger:data loaded to vector database successfullu
2024-01-18 22:30:41,761:logger:data loaded to vector database successfully
2024-01-18 22:30:56,411:logger:data loaded to vector database successfullu
2024-01-18 22:30:58,948:logger:data loaded to vector database successfully
2024-01-18 22:46:15,007:logger:data loaded to vector database successfullu
2024-01-18 22:47:32,135:logger:data loaded to vector database successfullu
2024-01-18 22:51:38,710:logger:data loaded to vector database successfullu
2024-01-18 22:51:46,255:logger:data loaded to vector database successfully
2024-01-18 23:00:10,087:logger:data loaded to vector database successfullu
2024-01-18 23:00:12,850:logger:data loaded to vector database successfully
2024-01-18 23:01:07,971:logger:data loaded to vector database successfullu
2024-01-18 23:01:10,469:logger:data loaded to vector database successfully
2024-01-18 23:15:41,385:logger:data loaded to vector database successfullu
2024-01-18 23:17:15,977:logger:data loaded to vector database successfullu
2024-01-18 23:17:52,516:logger:data loaded to vector database successfully
2024-01-18 23:23:03,695:logger:data loaded to vector database successfullu
2024-01-18 23:23:18,275:logger:data loaded to vector database successfullu
2024-01-18 23:25:49,760:logger:data loaded to vector database successfullu
2024-01-18 23:29:30,837:logger:data loaded to vector database successfully
2024-01-18 23:29:41,274:logger:automatic evaluation data generated succesfully.
2024-01-18 23:31:55,502:logger:data loaded to vector database successfullu
2024-01-18 23:31:59,037:logger:data loaded to vector database successfully
2024-01-18 23:32:18,499:logger:automatic evaluation data generated succesfully.
2024-01-18 23:34:41,772:logger:data loaded to vector database successfully
2024-01-18 23:34:55,869:logger:automatic evaluation data generated succesfully.
2024-01-19 19:52:57,690:logger:data loaded to vector database successfully
2024-01-19 19:53:08,505:logger:data loaded to vector database successfully
2024-01-19 19:53:09,268:logger:An unexpected error occurred: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-pW9Yf***************************************qF8E. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
2024-01-19 19:53:09,360:logger:An unexpected error occurred: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
2024-01-19 19:53:09,423:logger:An unexpected error occurred: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
2024-01-19 19:53:09,424:logger:An unexpected error occurred: 'NoneType' object has no attribute 'invoke'
2024-01-19 19:55:44,300:logger:data loaded to vector database successfully
2024-01-19 19:55:45,116:logger:An unexpected error occurred: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-pW9Yf***************************************qF8E. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
2024-01-19 19:55:45,211:logger:An unexpected error occurred: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
2024-01-19 19:55:45,270:logger:An unexpected error occurred: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
2024-01-19 19:55:45,270:logger:An unexpected error occurred: 'NoneType' object has no attribute 'invoke'
2024-01-19 19:58:20,619:logger:data loaded to vector database successfully
2024-01-19 19:58:24,235:logger:An unexpected error occurred: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-pW9Yf***************************************qF8E. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
2024-01-19 19:58:35,455:logger:An unexpected error occurred: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-pW9Yf***************************************qF8E. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
2024-01-19 19:58:46,019:logger:An unexpected error occurred: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
2024-01-19 20:03:36,364:logger:data loaded to vector database successfully
2024-01-19 20:03:38,295:logger:automatic evaluation data generated succesfully.
2024-01-19 20:03:38,364:logger:langchain with rag pipeline created successfully.
2024-01-19 20:03:38,426:logger:langchain with rag pipeline created successfully.
2024-01-19 20:03:42,437:logger:An unexpected error occurred: string indices must be integers, not 'str'
2024-01-19 20:06:24,695:logger:data loaded to vector database successfully
2024-01-19 20:06:26,196:logger:automatic evaluation data generated succesfully.
2024-01-19 20:06:26,267:logger:langchain with rag pipeline created successfully.
2024-01-19 20:06:26,333:logger:langchain with rag pipeline created successfully.
2024-01-19 20:10:24,578:logger:automatic evaluation data generated succesfully.
2024-01-19 20:13:19,463:logger:data loaded to vector database successfully
2024-01-19 20:13:21,752:logger:automatic evaluation data generated succesfully.
2024-01-19 20:13:21,842:logger:langchain with rag pipeline created successfully.
2024-01-19 20:13:21,913:logger:langchain with rag pipeline created successfully.
2024-01-19 20:13:33,736:logger:automatic evaluation data generated succesfully.
2024-01-19 20:29:50,040:logger:data loaded to vector database successfully
2024-01-19 20:29:51,708:logger:An unexpected error occurred: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-Hrgzs***************************************WlJy. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
2024-01-19 20:29:51,794:logger:An unexpected error occurred: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
2024-01-19 20:29:51,845:logger:An unexpected error occurred: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
2024-01-19 20:29:51,845:logger:An unexpected error occurred: 'NoneType' object has no attribute 'invoke'
2024-01-19 20:31:08,434:logger:data loaded to vector database successfully
2024-01-19 20:31:10,689:logger:automatic evaluation data generated succesfully.
2024-01-19 20:31:10,746:logger:langchain with rag pipeline created successfully.
2024-01-19 20:31:10,796:logger:langchain with rag pipeline created successfully.
2024-01-19 20:31:23,412:logger:automatic evaluation data generated succesfully.
2024-01-19 20:31:23,416:logger:An unexpected error occurred: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable
2024-01-19 20:35:44,712:logger:data loaded to vector database successfully
2024-01-19 20:35:46,960:logger:automatic evaluation data generated succesfully.
2024-01-19 20:35:47,038:logger:langchain with rag pipeline created successfully.
2024-01-19 20:35:47,097:logger:langchain with rag pipeline created successfully.
2024-01-19 20:35:59,762:logger:automatic evaluation data generated succesfully.
2024-01-19 20:35:59,765:logger:An unexpected error occurred: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable
